services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network
  nats-streaming:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
